'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmEntrySetup

    '''<summary>
    '''TxtAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSave As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''TxtUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUserID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUserName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPassword As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtConfirmPw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConfirmPw As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TabPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPage As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''BtnAllMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAllMenu As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''CbAlokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbAlokasi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbBank As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRekening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRekening As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbTipeForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbTipeForm As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbVendor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbKategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbKategori As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbProposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbProposal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbJob As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbNPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbNPWP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRAP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbEntrySPR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbEntrySPR As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalSPR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalSPR As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbInvoice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbClosingKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbClosingKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbKOAddendum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbKOAddendum As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbTrackingKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbTrackingKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbCancelPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbCancelPO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPD_KK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPD_KK As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPD_KT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPD_KT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPD_TBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPD_TBP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPD_DP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPD_DP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPD_DK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPD_DK As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRejectPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRejectPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbPJ As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalPJ As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbPaymentPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbPaymentPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRPPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRPPM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRPPM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRPPM1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbTermin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbTermin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRencanaTermin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRencanaTermin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbApprovalTermin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbApprovalTermin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbCOA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbCOA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbGlReff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbGlReff As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbIdentitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbIdentitas As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbJurnalEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbJurnalEntry As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbJurnalApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbJurnalApproval As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbExportJurnal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbExportJurnal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbQueryJurnal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbQueryJurnal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRekapKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRekapKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbTrackKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbTrackKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbInvReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbInvReceipt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbItemPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbItemPrice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbQueryAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbQueryAP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRAPKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRAPKO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbDPPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbDPPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRekapPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRekapPayment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbSerapRAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbSerapRAP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbQueryPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbQueryPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbRealisasiTermin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbRealisasiTermin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbSRPengeluaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbSRPengeluaran As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbCashFlow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbCashFlow As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbQueryTermin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbQueryTermin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbPiuProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbPiuProgress As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbResumePK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbResumePK As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbLapKeu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbLapKeu As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbLR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbLR As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbBukuBesar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbBukuBesar As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbBukuTambahan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbBukuTambahan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbNeracaMutasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbNeracaMutasi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbNotaAkuntansi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbNotaAkuntansi As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbTrackPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbTrackPD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbOverrideSaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbOverrideSaldo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbSetup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbPasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbPasswd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CbMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CbMessage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''BtnAllAlokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAllAlokasi As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl3 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''BtnAllJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAllJob As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridData As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''msgBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgBox1 As Global.BunnyBear.msgBox
End Class
