'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmRencanaTermin

    '''<summary>
    '''PopEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntry As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl2 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''DDLJenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLJenis As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''TxtTglRencana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTglRencana As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''TxtUraian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUraian As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''TxtPersentase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPersentase As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtA As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtB As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtC As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtD As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUM As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtE As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtF As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtG As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtH As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtI As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJ As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtK As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtL As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''BtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSave As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''LblAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTglRencana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTglRencana As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblJenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblJenis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLJob As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''BtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''MsgBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBox1 As Global.BunnyBear.msgBox
End Class
