'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmShareTermin

    '''<summary>
    '''ErrMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrMsg As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''LblErr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblErr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClose As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''PopEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopEntry As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl2 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''TxtAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TglShare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TglShare As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''LblMember1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMember1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtTermin1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTermin1 As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtTerminKSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTerminKSO As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''LblMember2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMember2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtTermin2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTermin2 As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''TxtKeterangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtKeterangan As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''BtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSave As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''DDLJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLJob As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''BtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAdd As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''GridData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridData As Global.System.Web.UI.WebControls.GridView
End Class
